# DISCRIMINANT ANALYSIS

In this coding assignment you are to implement a Minimum Risk Bayes Decision Theoretic classifier. Use the training set to train the classifier and the validation set to evaluate the accuracy.

Assume the following:
1. All conditional density functions are multivariate Gaussian
2. Each class has its own covariance matrix
3. Equal prior probabilities
4. 0-1 loss function


## Load datasets

In [48]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load training data - 135 observations, 4 features, 3 classes,
df = pd.read_csv("iris_corrupted_training_dataset.csv")
print(df.head())
df = df.values
train_data = df

# Load validation data - 15 samples
df = pd.read_csv("iris_validation_dataset.csv")
print(df.head())
df = df.values
val_data = df

   sepal_length   sepal_width   petal_length   petal_width   class
0        5.7147        2.6743         3.2696       1.65440       2
1        5.1734        3.7374         5.9442       3.00050       3
2        7.3776        3.1505         3.3543       0.64839       2
3        6.4908        2.3983         3.3917       1.54950       2
4        6.8182        3.4016         4.7495       0.57970       3
   sepal_length   sepal_width   petal_length   petal_width   class
0           4.4           2.9            1.4           0.2       1
1           6.7           3.0            5.2           2.3       3
2           4.9           3.1            1.5           0.2       1
3           5.1           2.5            3.0           1.1       2
4           6.1           3.0            4.6           1.4       2


In [49]:
## Your code goes here ...

X=train_data[:,0:4]
Y=train_data[:,4]
X_val=val_data[:,0:4]
Y_val=val_data[:,4]
mean={}
covariance={}
classes=np.unique(Y)
prior_probability=1/(len(classes))

X_train={}

for i in classes:
  X_train[i]=X[Y==i]

#Calculate mean and covariance
for i in classes:
  mean[i]=np.mean(X_train[i],axis=0)
  covariance[i]=np.cov(X_train[i],rowvar=False)

  print(f"class {i}")
  print(f"mean: {mean[i]}")
  print(f"covariance: {covariance[i]}")


#Calculate determinant
def predict(x_value):
  log_pdf=np.zeros((x_value.shape[0],len(classes)))
  for x,val in enumerate(x_value):
    for i,c in enumerate(classes):
      d=X.shape[1]
      diff=val-mean[c]
      sign,logdet=np.linalg.slogdet(covariance[c])
      cov_diff=np.linalg.solve(covariance[c],diff)
      mahalanobis=np.dot(diff,cov_diff)
      log_pdf[x,i]= -0.5*(d*np.log(2*np.pi)) -0.5*(logdet) -.5*mahalanobis +np.log(prior_probability)
  return log_pdf



class 1.0
mean: [4.80081778 3.48799556 1.26920989 0.34787733]
covariance: [[ 0.73847372 -0.09788292  0.162097    0.09430334]
 [-0.09788292  1.04517177  0.08250472  0.06122466]
 [ 0.162097    0.08250472  0.75386746  0.07747734]
 [ 0.09430334  0.06122466  0.07747734  0.51347455]]
class 2.0
mean: [6.06588222 2.82287978 4.26241333 1.10785197]
covariance: [[ 1.02666705  0.16051089  0.28736137 -0.10850815]
 [ 0.16051089  0.80414317  0.20221368 -0.07318826]
 [ 0.28736137  0.20221368  0.74048204 -0.04380217]
 [-0.10850815 -0.07318826 -0.04380217  0.69674064]]
class 3.0
mean: [6.42966    2.95656956 5.55874667 1.92476547]
covariance: [[1.36272732 0.26608677 0.44568822 0.30336696]
 [0.26608677 1.03934606 0.12853287 0.18437967]
 [0.44568822 0.12853287 0.69605886 0.23021863]
 [0.30336696 0.18437967 0.23021863 0.85756954]]


In [50]:
#Validation
log_value=predict(X_val)
predicted_indices=np.argmax(log_value,axis=1)
predictedClass=classes[predicted_indices]

print("Results")
for i in range(len(predictedClass)):
  print(f"y={Y_val[i]}, y_hat={predictedClass[i]}")
  accuracy=(np.sum(Y_val==predictedClass))/len(Y_val)

print (accuracy)
print(f"Average classification accuracy: {accuracy}")
print(f"Average accuracy: {(accuracy*100):.4f}%")

Results
y=1.0, y_hat=1.0
y=3.0, y_hat=3.0
y=1.0, y_hat=1.0
y=2.0, y_hat=2.0
y=2.0, y_hat=2.0
y=1.0, y_hat=1.0
y=2.0, y_hat=2.0
y=1.0, y_hat=1.0
y=2.0, y_hat=3.0
y=3.0, y_hat=3.0
y=3.0, y_hat=3.0
y=3.0, y_hat=3.0
y=2.0, y_hat=2.0
y=3.0, y_hat=3.0
y=1.0, y_hat=1.0
0.9333333333333333
Average classification accuracy: 0.9333333333333333
Average accuracy: 93.3333%
